name: Triggers
run-name: ¡I learn to uses different Triggers!

on:
  push:
    branches: ["aprendiendo-github-actions" , "main"]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Favorite languages'
        default: Python
        required: true
        type: choice
        options:
        - Python
        - JavaScript
        - Go
      nombre:
        description: 'Your name'
        required: true
        default: Juan
        type: string
  schedule:
    - cron:  '15 22 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Definir nombre
        run: echo "USERNAME=${{inputs.nombre}}" >> $GITHUB_ENV

      - name: Definir lenguaje
        run: echo "LANGUAGE=${{inputs.lenguaje_favorito}}" >> $GITHUB_ENV

      - name: Correr script
        run: python hola_lenguaje.py

      - name: Verificar variables
        run: |
          echo "USERNAME: $USERNAME"
          echo "LANGUAGE: $LANGUAGE"

  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_mundo.py
